AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 Bucket for Log Storage

Resources:
  MyStudyLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      # No BucketName specified to allow CloudFormation to generate a unique name
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: AWS-Study-Log
        - Key: Environment
          Value: Dev

Outputs:
  BucketName:
    Value: !Ref MyStudyLogBucket
    Description: Name of the S3 bucket created