AWSTemplateFormatVersion: '2010-09-09'
Description: Advanced S3 Bucket with Versioning and Lifecycle Rules

Resources:
  MyAdvancedLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      # Versioning Setting to avoid miss operaition
      VersioningConfiguration:
        Status: Enabled
      # Life Cycle setting
      LifecycleConfiguration:
        Rules:
          - Id: CostSavingRule
            Status: Enabled
            # Change to ceap class IA over 30 days
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
            
            # Delete when one year passed
            ExpirationInDays: 365

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      
      Tags:
        - Key: Project
          Value: AWS-Study-Log
        - Key: Environment
          Value: Dev

Outputs:
  BucketName:
    Value: !Ref MyAdvancedLogBucket
    Description: Name of the advanced S3 bucket
