AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 Test
    
Resources:    
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-068c0051b15cdb816
      InstanceType: t3.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: subnet-038ab9b0361287662
          GroupSet:
            - !Ref secGroupName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf update -y
          dnf install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Welcome to AWS EC2 Web Server</h1>" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: cfn-web-server
  secGroupName:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: cfn-web-sg
      GroupDescription: Allow HTTP traffic
      VpcId: vpc-0d198d8feec967e62
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0